spring:
  profiles:
    active: common, secret

---

spring.config.activate.on-profile: common

spring:
#  Metadata
  application.name: junggo
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/swagger-ui/

#  Persistence
  sql.init.mode: always
  r2dbc:
    enabled: true
    url: r2dbc:h2:mem:///test;MODE=MySQL
    username: sa
    password:
    pool:
      enabled: true
      max-size: 20
  data:
    r2dbc.repositories:
      enabled: true
  main.allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

oauth2:
  google:
    client-id: 258128970331-b27sucjs4damtokr699gbl3k1m6ca85s.apps.googleusercontent.com
    token-url: https://oauth2.googleapis.com/token
  kakao:
    client-id: 40238f34fbc22b3068fce125cae3aad3
    token-url: https://kauth.kakao.com/oauth/token
  github:
    client-id: Ov23ctXu2evZUSK3lHVV
    token-url: https://github.com/login/oauth/access_token
  redirect-uri: http://localhost:3000/callback

server:
  port: 8094

springdoc:
  api-docs:
    path: /api-docs
    groups.enabled: true
  swagger-ui:
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  root: INFO
  org:
    springframework:
      data.r2dbc: TRACE

# PortOne(아임포트) API 설정 추가
portone:
  api-key: "YOUR_PORTONE_API_KEY"
  api-secret: "YOUR_PORTONE_API_SECRET"


