spring:
  profiles:
    active: common, secret

---

spring.config.activate.on-profile: common

spring:
#  Metadata
  application.name: junggo
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/swagger-ui/

#  Persistence
  sql.init.mode: never
  r2dbc:
    enabled: true
    url: r2dbc:mysql://aws-mysql.cdss0m0yyvd2.ap-northeast-2.rds.amazonaws.com:3306/vintage_focus
    username: vintage_focus
    password: doc13qQq
    pool:
      enabled: true
      max-size: 20
  data:
    r2dbc.repositories:
      enabled: true

  main.allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 600000
oauth2:
  google:
    token-url: https://oauth2.googleapis.com/token
  kakao:
    user-info:
      url: https://kapi.kakao.com/v2/user/me
      column-username: properties.nickname
      column-profile: properties.thumbnail_image
    token-url: https://kauth.kakao.com/oauth/token
  github:
    user-info:
      url: https://api.github.com/user
      column-username: login
      column-profile: avatar_url
    token-url: https://github.com/login/oauth/access_token
  redirect-uri: http://localhost:3000/callback

server:
  port: 8094

springdoc:
  api-docs:
    path: /api-docs
    groups.enabled: true
  swagger-ui:
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  root: DEBUG
  org:
    springframework:
      data.r2dbc: TRACE


portone:
  api-key: ${PORTONE_API_KEY}
  api-secret: ${PORTONE_API_SECRET}