spring:
  sql.init.mode: never
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: vintage_focus
    password: ${SPRING_R2DBC_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 600000

logging.level.root: WARN

portone:
  api-key: ${PORTONE_API_KEY}
  api-secret: ${PORTONE_API_SECRET}

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
  github:
    client-id: ${GH_CLIENT_ID}
    client-secret: ${GH_CLIENT_SECRET}
  redirect-uri: http://vintage-focus.s3-website.ap-northeast-2.amazonaws.com/callback
#  redirect-uri: http://localhost:3000/callback

client-uri: vintage-focus.s3-website.ap-northeast-2.amazonaws.com