spring:
  sql.init.mode: never

logging.level.root: WARN



oauth2:

  redirect-uri: http://vintage-focus.s3-website.ap-northeast-2.amazonaws.com/callback
#  redirect-uri: http://localhost:3000/callback

client-uri: vintage-focus.s3-website.ap-northeast-2.amazonaws.com