export const dummyReviews = [
    {
      id: Date.now() + 1,
      title: "소니 A7 III 매각합니다.",
      content: "구입 후 2년 정도 사용했습니다. 스크래치 거의 없고 상태 양호합니다.",
      product: {
        name: "Sony A7 III",
        imageUrl: "/image/sony-a7iii.jpg",
      },
      author: { name: "김철수", avatar: "/static/images/avatar/default.png" },
      locked: false,
      tag: "매각문의",
      date: new Date().toISOString().split('T')[0],
      views: 45,
      price: "1,500,000원",
    },
    {
      id: Date.now() + 2,
      title: "니콘 Z6 II 중고 구매 원합니다.",
      content: "니콘 Z6 II 바디 중고 구매 희망합니다. 배터리 포함이면 좋겠습니다.",
      product: {
        name: "Nikon Z6 II",
        imageUrl: "/image/nikon-z6ii.jpg",
      },
      author: { name: "박영희", avatar: "/static/images/avatar/default.png" },
      locked: false,
      tag: "구매문의",
      date: new Date().toISOString().split('T')[0],
      views: 32,
      price: "예산: 1,200,000원",
    },
    {
      id: Date.now() + 3,
      title: "캐논 EOS R6 단기 대여 희망합니다.",
      content: "여행 중 사용할 용도로 Canon EOS R6 대여하고 싶습니다. 렌즈 포함이면 좋겠습니다.",
      product: {
        name: "Canon EOS R6",
        imageUrl: "/image/rental2.jpg",
      },
      author: { name: "이민호", avatar: "/static/images/avatar/default.png" },
      locked: false,
      tag: "대여문의",
      date: new Date().toISOString().split('T')[0],
      views: 27,
      price: "대여비 협의",
      rental: {
        rentalLocation: "김포공항점",
        startDate: "2025-04-01T10:00:00.000Z",
        startTime: "10:00 AM",
        returnDate: "2025-04-07T18:00:00.000Z",
        returnTime: "6:00 PM",
        lat: 37.55868,
        lng: 126.79445,
      },
    },
    {
      id: Date.now() + 4,
      title: "후지필름 X-T4 매각합니다.",
      content: "박스 및 구성품 모두 포함된 상태로 판매합니다. 실 사용감 적습니다.",
      product: {
        name: "Fujifilm X-T4",
        imageUrl: "/image/fuji-xt4.jpg",
      },
      author: { name: "오진수", avatar: "/static/images/avatar/default.png" },
      locked: false,
      tag: "매각문의",
      date: new Date().toISOString().split('T')[0],
      views: 50,
      price: "1,300,000원",
    },
    {
      id: Date.now() + 5,
      title: "소니 A7C 구매 원합니다.",
      content: "Sony A7C 바디 및 렌즈 포함해서 구매 원합니다. 좋은 가격으로 구매 희망합니다.",
      product: {
        name: "Sony A7C",
        imageUrl: "/image/sony-a7c.jpg",
      },
      author: { name: "강민석", avatar: "/static/images/avatar/default.png" },
      locked: false,
      tag: "구매문의",
      date: new Date().toISOString().split('T')[0],
      views: 38,
      price: "예산: 1,400,000원",
    },
    {
      id: Date.now() + 6,
      title: "니콘 Z fc 단기 대여 희망합니다.",
      content: "출사 여행 중 사용할 용도로 니콘 Z fc 대여 원합니다. 배터리 포함 필수.",
      product: {
        name: "Nikon Z fc",
        imageUrl: "/image/rental.jpg",
      },
      author: { name: "조현우", avatar: "/static/images/avatar/default.png" },
      locked: false,
      tag: "대여문의",
      date: new Date().toISOString().split('T')[0],
      views: 22,
      price: "대여비 협의",
      rental: {
        rentalLocation: "인천국제공항점",
        startDate: "2025-04-03T09:00:00.000Z",
        startTime: "9:00 AM",
        returnDate: "2025-04-09T20:00:00.000Z",
        returnTime: "8:00 PM",
        lat: 37.44735,
        lng: 126.45052,
      },
    }
  ];
  