name: Blue-Green Deployment

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      run: |
        docker build \
          --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          --build-arg PORTONE_API_KEY=${{ secrets.PORTONE_API_KEY }} \
          --build-arg PORTONE_API_SECRET=${{ secrets.PORTONE_API_SECRET }} \
          --build-arg OAUTH_PROVIDERS=${{ secrets.OAUTH_PROVIDERS }} \
          --build-arg GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}\
          --build-arg GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}\
          --build-arg KAKAO_CLIENT_ID=${{secrets.KAKAO_CLIENT_ID}}\
          --build-arg KAKAO_CLIENT_SECRET=${{secrets.KAKAO_CLIENT_SECRET}}\
          --build-arg GH_CLIENT_ID=${{secrets.GH_CLIENT_ID}}\
          --build-arg GH_CLIENT_SECRET=${{secrets.GH_CLIENT_SECRET}}\
          --build-arg SPRING_R2DBC_URL=${{ secrets.SPRING_R2DBC_URL }} \
          --build-arg SPRING_R2DBC_PASSWORD="${{ secrets.SPRING_R2DBC_PASSWORD }}" \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/vintage-focus:latest ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/vintage-focus:latest
